import type { Metadata } from 'next'
import { BtmBar } from '../ui/common/BtmBar'
import { BackAppbar, MainAppbar } from '../ui/common/appbar'

export const metadata: Metadata = {
  title: '로카 플레이스',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div className="w-full h-full flex-col flex ">
      <div className="px-4">
        <BackAppbar />
      </div>
      {children}
      <div className="h-16" />
    </div>
  )
}
