import type { Metadata } from 'next'

import './globals.css'

export const metadata: Metadata = {
  title: '로카 플레이스',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={` antialiased font-['Spoqa Han Sans Neo'] `}>
        <div className="w-full py-3.5">{children}</div>
      </body>
    </html>
  )
}
