import type { Metadata } from 'next'

import './globals.css'

export const metadata: Metadata = {
  title: '로카 플레이스',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={` antialiased font-['Spoqa Han Sans Neo'] `}>
        <div className="w-full py-3.5">{children}</div>
      </body>
      {/* <script defer async>
        {`
            function getMessage (bridgeName, value) {
  switch (bridgeName) {
    case 'login':
      console.log("asdf")
      // 딥링크로 앱에 진입했을 때 수행 코드를 작성합니다.
    case 'notification':
      // push notification 클릭시 수행 코드를 작성합니다.
    case 'colorScheme':
      // 다크모드 변경시 수행 코드를 작성합니다.
  }
}
          `}
      </script> */}
    </html>
  )
}
