import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: '로카 플레이스',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return <div className="bg-white w-full px-4">{children}</div>
}
