import type { Metadata } from 'next'
import { BtmBar } from '../ui/common/BtmBar'
import { MainAppbar } from '../ui/common/appbar'

export const metadata: Metadata = {
  title: '로카 플레이스',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div className="w-full h-full flex-col flex px-4">
      <MainAppbar />
      {children}
      <div className="h-16" />
      <BtmBar />
    </div>
  )
}
